version: '2.2'

services:
  srsepc:
    container_name: virtual-srsepc
    build: .
    command:
      - srsepc
      - epc.conf
    network_mode: "host"
    privileged: true
    volumes:
      - ./logs:/tmp
  srsenb:
    container_name: virtual-srsenb
    build: .
    command:
      - srsenb
      - enb.conf
    network_mode: "host"
    privileged: true
    volumes:
      - ./logs:/tmp
    depends_on:
        - srsepc
